### ISSUE TITLE
`block (2 levels) in list_ips': undefined method `create_proxy' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by jlestel** [wvandevanter-r7/gatling_gun#1]
Hello, 

Where is the method "create_proxy" ??

Thx :)

**Comment by wvandevanter-r7** [comment]
hi! I apologize this code needs a major overhaul, wasn't sure if people were still using it. I just pushed a fix that should get around this bug you pointed out atleast.

**Comment by jlestel** [comment]
Thx :)
